version: "3.3"

services:
  mysql:
    image: mysql:5.7
    container_name: dev_cariapo_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysqldev
  redis:
    image: redis:6.0.6
    container_name: dev_cariapo_redis
    restart: always
    ports:
      - 6379:6379
