version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elastic_server
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    ports:
      - 9200:9200
  #kibana:
  #  image: docker.elastic.co/kibana/kibana:7.5.2
  #  container_name: kibana_server
  #  ports:
  #    - 5601:5601
