version: '3.1'

services:
  ghost:
    image: ghost
    restart: always
    ports:
      - 8001:2368
    environment:
      database__client: mysql
      database__connection__host: 'host'
      database__connection__user: 'user'
      database__connection__password: 'password'
      database__connection__database: 'dbname'
      url: 'https://test.com'