version: "3.7"

services:
  zookeeper-server:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    networks:
      - prod
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    networks:
      - prod
    ports:
      - '9093:9093'
    volumes:
      - 'kafka_data:/bitnami/kafka'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper-server

volumes:
  zookeeper_data: null
  kafka_data: null

networks:
  prod:
    driver: bridge
    name: prod