version: '3.1'

services:
  redis:
    image: redis:6.0.6
    container_name: dev_redis
    command: redis-server --requirepass password # change password
    image: redis:5.0.6-alpine
    restart: always
    ports:
      - 6379:6379
