version: "3.3"

services:
  redis:
    container_name: redis
    command: redis-server --requirepass password # change password
    image: redis:5.0.6-alpine
    restart: always
    ports:
      - 6379:6379
